configuration: Release

version: 2.0.{build}

image: Visual Studio 2017

build:
    parallel: true
    publish_nuget: true
    verbosity: minimal

before_build:
  - dotnet restore
  
branches:
    only:
      - master

deploy:
  provider: NuGet
  api_key:
    secure: PcXqIhdC7ZETvlKSX4Zd5kgSp8OoLl59L1T5S9QLuYY=
  skip_symbols: false
  artifact: /.*\.nupkg/
  
    

  
  


